name: Dristi-kerala Image Build workflow
on:
  push:
    branches:
      - e-sign
  workflow_dispatch:

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Build and Push Docker image for advocate
        run: |
          docker build --build-arg WORK_DIR="backend/esign-spring-boot" -t pucarsolutionsdev.azurecr.io/e-sign:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/e-sign:v1.0.0-${{ github.sha }}
