name: Epost Tracker Image Build workflow
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
    paths:
      - 'backend/epost-tracker/**'
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and analyze for Epost Tracker
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B -f backend/epost-tracker/pom.xml package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=solutions_epost_tracker -Dsonar.organization=solutions -Dsonar.host.url=https://sonarcloud.io/

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Get Merge commit of PR
        run: |
          PR_NUMBER=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | jq -r '.[0].number')
          Merge_Commit=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.merge_commit_sha')
          echo "Merge_Commit=$Merge_Commit" >> $GITHUB_ENV

      - name: Build and Push Docker image for Epost Tracker
        run: |
          docker build --build-arg WORK_DIR="backend/epost-tracker" -t pucarsolutionsdev.azurecr.io/epost-tracker:v1.0.0-${{ env.Merge_Commit }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/epost-tracker:v1.0.0-${{ env.Merge_Commit }}

      - name: Build and Push Docker image for Epost Tracker DB
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/epost-tracker-db:v1.0.0-${{ env.Merge_Commit }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/epost-tracker-db:v1.0.0-${{ env.Merge_Commit }}
        working-directory: backend/epost-tracker/src/main/resources/db

  Workflow_Trigger:
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Trigger Deployment Pipeline for Solutions Dev
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/solutions-dev.yaml/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'
