name: Digit-UI Image Build workflow
on:
  push:
    branches:
      - sdc-ui

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io


      - name: Build and Push Docker image for digit-ui
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/digit-ui:v1.0.0-SDC -f  web/docker/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/digit-ui:v1.0.0-SDC
        working-directory: frontend/micro-ui


