name: OCR-service Image Build workflow
on:
  push: 
    paths:
      - 'backend/ocr-service/**'
  pull_request:
    types:
      - closed
    branches:
      - develop
    paths:
      - 'backend/ocr-service/**'
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io


      - name: Build and Push Docker image for Ocr-Service
        run: |
          docker build --build-arg WORK_DIR="backend/advocate" -t pucarsolutionsdev.azurecr.io/pucar_ocr_svc:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pucar_ocr_svc:v1.0.0-${{ github.sha }}

      - name: Build and Push Docker image for Ocr-Service_DB
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/pucar_ocr_svc_db:v1.0.0-${{ github.sha }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pucar_ocr_svc_db:v1.0.0-${{ github.sha }}
        working-directory: backend/ocr-service/src/main/resources/db
